version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mrooj-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: mrooj_db
      MYSQL_USER: mrooj_user
      MYSQL_PASSWORD: MroojDB@2026
      MYSQL_ROOT_PASSWORD: MroojRoot@2026

    ports:
      - "3306:3306"

    volumes:
      - mrooj_mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMroojRoot@2026"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mrooj_mysql_data: